# fly.toml app configuration file generated for estores-vienna on 2024-12-12T17:48:41+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'estores-vienna'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'postgres'
  destination = '/postgres-volume'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
