# fly.toml app configuration file generated for estores on 2024-12-12T17:48:41+01:00
#
#

app = 'estores'
primary_region = 'otp'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'postgres'
  destination = '/postgres-volume'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
